# Generated by Django 5.0.3 on 2024-05-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('category', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=256)),
                ('provider', models.CharField(max_length=256)),
                ('duration', models.CharField(max_length=32)),
                ('price', models.CharField(max_length=32)),
                ('rating', models.CharField(max_length=32)),
            ],
        ),
    ]
