# Generated by Django 4.1 on 2023-01-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("category", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=32)),
                ("description", models.CharField(max_length=32)),
            ],
        ),
    ]
