# Generated by Django 5.0.3 on 2024-05-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_course_description_alter_course_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='course',
            name='provider',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
